### ISSUE TITLE
WinPwnage sets is outdated

### ISSUE THREAD

**Issue by rootm0s** [n0dec/MalwLess#1]
Not sure if you still maintain this project, but WinPwnage received tons of updates since your last PR

**Comment by n0dec** [comment]
Hi @rootm0s , thanks for the info. The main goal of sets is that the community shares and creates new sets, so feel free if you want to submit a PR with those. However, I'll create some if I have the chance.

**Comment by rootm0s** [comment]
@n0dec Thanks for the reply, there's a lot to cover if I'm going to create new sets and I don't have the time, but maybe in the future ill help out!
